### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by pioneer911** [poria72/Action#1]
Can you tell me which paper you refer and how to use your code ? Thanks a lot.

**Comment by poria72** [comment]
Hi.
At The Moment I'm Working on My Paper so There is No Paper For This Codes, Yet. In Addition, I'm Developing This Codes. But I Can Help You Using This Codes. If You Want, Please Tell Me Which part of the code is required?

**Comment by pioneer911** [comment]
Hi,I am a novice in behavior recognition, I see the use of convolution neural network in your code, can you talk about  the idea of this article?In addition, What's the hardware condition for the other code to run?Thanks a lot.

**Comment by poria72** [comment]
these codes use a pre-trained CNN that trained on ImageNet dataset in Caffe for feature extraction from video Frames and classification (For Action Recognition). I used MatConvNet to working with the neural network in Matlab. see this link: http://www.vlfeat.org/matconvnet/
About hardware, I can say that Using the pre-trained CNN doesn't need a powerful hardware. I run this codes on my laptop and in CPU Mode (Core i7 3610QM and 8GB Ram).
but if you want to train a CCN yourself,  you'll need a Stronger system.
